version: '2'
services:
  play-engine-choices:
    image: stevejr/play-engine-choices:1
    build: ./choicepoll/Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - MONGO_USER
      - MONGO_PASSWORD
    networks:
      - playengine-network
    depends_on:
      - playengine
  play-engine-results:
    image: stevejr/play-engine-results:1
    build: ./resultspoll/Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - MONGO_USER
      - MONGO_PASSWORD
    networks:
      - playengine-network
    depends_on:
      - playengine
  playengine:
    image: johnharris85/play-engine
    build: .
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - MONGO_USER
      - MONGO_PASSWORD
    networks:
      - playengine-network
    ports:
     - "5000:5000"
networks:
  playengine-network:
